//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION
    {
        public int registration_id { get; set; }
        public int client_id { get; set; }
        public int employee_id { get; set; }
        public int services_id { get; set; }
        public System.DateTime registration_date { get; set; }
        public int status { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual SERVICES SERVICES { get; set; }
        public virtual STATUS STATUS1 { get; set; }
    }
}
